name: Update Front End Jobs Data
on:
  workflow_dispatch:
jobs:
  update-data:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Install dependencies
        run: |
          npm install
          npm install -g ts-node
      - name: Run script to update Front-End Jobs Data
        run: npx ts-node scripts/update-jsearch-front-end-jobs.ts
        env:
          RAPIDAPI_KEY_JSEARCH: ${{ secrets.RAPIDAPI_KEY_JSEARCH }}
      - name: Add, Commit and Push New Jobs Data
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add data/jsearch-front-end.json
          git commit -m "update front end jobs data"
          git push origin main
        continue-on-error: true
